//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store4.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public System.Guid Id { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public System.Guid CountryId { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
