//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTNET.Solution.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.Guid CountryId { get; set; }
        public bool IsGeographical { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
